-- the-world isolated schema / tables
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  email text not null,
  is_admin boolean not null default true,
  created_at timestamp with time zone default now()
);
create unique index if not exists admin_users_email_idx on public.admin_users (email);

create table if not exists public.site_settings (
  key text primary key,
  value text,
  updated_at timestamp with time zone default now()
);

create table if not exists public.theworld_products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'unisexe',
  price numeric not null default 0,
  stock integer not null default 0,
  images text,
  description text,
  created_at timestamp with time zone default now()
);

create table if not exists public.theworld_orders (
  id bigint generated by default as identity primary key,
  status text not null default 'pending',
  items jsonb not null default '[]'::jsonb,
  total numeric not null default 0,
  customer_name text,
  customer_phone text,
  customer_email text,
  shipping_address text,
  user_id text,
  created_at timestamp with time zone default now()
);
